---
# Handlers file for hardening role

- name: Reboot
  reboot:
    reboot_timeout: 600

- name: Restart auditd
  service:
    name: auditd
    state: restarted

- name: Restart firewalld
  service:
    name: firewalld
    state: restarted
