---
# CrowdSec collections, configurations and bouncers installation

- name: Add crowdsec-firewall-bouncer-iptables package Ubuntu
  apt:
    name: crowdsec-firewall-bouncer-iptables
    state: present
  become: true
  notify: Restart crowdsec
  when: ansible_os_family == "Debian"

- name: Add crowdsec-firewall-bouncer-iptables package EL/CentOS 7 & Amazon
  yum:
    name: crowdsec-firewall-bouncer-iptables
    state: present
  become: true
  notify: Restart crowdsec
  when: >
    ((ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux') and
    ansible_distribution_major_version == "7") or
    ansible_distribution == 'Amazon'

- name: Add crowdsec-firewall-bouncer-iptables package EL/CentOS 8 & EL/CentOS 9
  dnf:
    name: crowdsec-firewall-bouncer-iptables
    state: present
  become: true
  notify: Restart crowdsec
  when:
    - ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
    - ansible_distribution_major_version == "8" or ansible_distribution_major_version == "9"

- name: Get installed collections
  command: cscli collections list
  changed_when: false
  become: true
  register: collections

- name: Install base-http-scenarios collection
  command: cscli collections install crowdsecurity/base-http-scenarios
  when: "'base-http-scenarios' not in collections.stdout"
  become: true
  notify: Restart crowdsec

- name: Install http-cve collection
  command: cscli collections install crowdsecurity/http-cve
  when: "'http-cve' not in collections.stdout"
  become: true
  notify: Restart crowdsec

- name: Install whitelist-good-actors collection
  command: cscli collections install crowdsecurity/whitelist-good-actors
  when: "'whitelist-good-actors' not in collections.stdout"
  become: true
  notify: Restart crowdsec

- name: Install apache2 collection
  command: cscli collections install crowdsecurity/apache2
  when: "'apache2' not in collections.stdout"
  become: true
  notify: Restart crowdsec

- name: Install nginx collection
  command: cscli collections install crowdsecurity/nginx
  when: "'nginx' not in collections.stdout"
  become: true
  notify: Restart crowdsec

- name: Install smb collection
  command: cscli collections install crowdsecurity/smb
  when: "'smb' not in collections.stdout"
  become: true
  notify: Restart crowdsec

- name: Install linux-lpe collection
  command: cscli collections install crowdsecurity/linux-lpe
  when: "'linux-lpe' not in collections.stdout"
  become: true
  notify: Restart crowdsec

- name: Get installed scenarios
  command: cscli scenarios list
  changed_when: false
  become: true
  register: scenarios

- name: Install mail-generic-bf scenario
  command: cscli scenarios install hitech95/mail-generic-bf
  when: "'mail-generic-bf' not in scenarios.stdout"
  become: true
  notify: Restart crowdsec

