---
# Tasks file for crowdsec-plus-console

# - fail:
#     msg: "bailing out, this role requires 'crowdsec_enroll_key'  and 'crowdsec_enroll_name' to be defined."
#   when:
#   - crowdsec_enroll_key is not defined
#   - crowdsec_enroll_name is not defined

- name: Check if CrowdSec is already installed
  stat:
    path: /etc/crowdsec/
  register: crowdsec_installed

- name: "Debug crowdsec_installed"
  debug:
    msg: "crowdsec_installed variable: {{ crowdsec_installed }}"

- name: Download crowdsec repo install script
  get_url:
    url: https://packagecloud.io/install/repositories/crowdsec/crowdsec/script.deb.sh
    dest: /root/crowdsecinstaller.sh
    mode: 0755
  become: true
  when: not crowdsec_installed.exists

- name: Execute CrowdSec repo install script
  command: /root/crowdsecinstaller.sh
  become: true
  when: not crowdsec_installed.exists

- name: Remove the CrowdSec repo install script
  file:
    path: /root/crowdsecinstaller.sh
    state: absent

- name: Add CrowdSec package
  apt:
    name: crowdsec
    state: present
  become: true

- name: Add crowdsec-firewall-bouncer-iptables package
  apt:
    name: crowdsec-firewall-bouncer-iptables
    state: present
  become: true

- name: Check if CrowdSec dashboard has been setup
  stat:
    path: /etc/crowdsec/metabase/metabase.yaml
  register: dashboard_setup

- name: Add docker.io package
  apt:
    name: docker.io
    state: present
  become: true

- name: Setup CrowdSec dashboard
  command: cscli dashboard setup
  become: true
  when: not dashboard_setup.exists

# - name: install whitelist-good-actors collection
#   shell: cscli collections install crowdsecurity/whitelist-good-actors
#   when: crowdsec_whitelist_good_actors | bool
#   become: true

# - name: enrolls this machine to crowdsec console
#   command: cscli console enroll --name {{ crowdsec_enroll_name }} {{ crowdsec_enroll_key }}
#   become: true

...
