---
# Tasks file for crowdsec-plus-console

# - fail:
#     msg: "crowdsec role requires 'crowdsec_enroll_key' and 'crowdsec_enroll_name' to be defined"
#   when:
#   - crowdsec_enroll_key is not defined
#   - crowdsec_enroll_name is not defined

- name: Installation for Ubuntu
  include_tasks: install_ubuntu.yml
  when: ansible_os_family == "Debian"

- name: Installation for EL/CentOS 7
  include_tasks: install_el7.yml
  when:
    - ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
    - ansible_distribution_major_version == "7"

- name: Installation for Amazon Linux
  include_tasks: install_el7.yml
  when: ansible_distribution == 'Amazon'

- name: Installation for EL/CentOS 8 & EL/CentOS 9
  include_tasks: install_el8.yml
  when:
    - ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
    - ansible_distribution_major_version == "8" or ansible_distribution_major_version == "9"

- name: Add collections
  include_tasks: collections.yml

- name: Set CrowdSec console variables
  set_fact:
    crowdsec_enroll_name: "{{ lookup('env', 'CONSOLE_NAME') }}"
    crowdsec_enroll_key: "{{ lookup('env', 'CONSOLE_KEY') }}"

- name: Enroll to CrowdSec console
  command: cscli console enroll --overwrite --name {{ crowdsec_enroll_name }} {{ crowdsec_enroll_key }}
  become: true
  changed_when: false

- name: CrowdSec Dashboard setup
  include_tasks: setup_dashboard.yml
...
