---
# Install and enable firewalld service

- name: Install the latest version of firewalld Ubuntu
  apt:
    name: firewalld
    state: present
  when: ansible_os_family == "Debian"

- name: Install the latest version of firewalld EL/CentOS 7 & Amazon
  yum:
    name: firewalld
    state: present
  when: >
    ((ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux') and
    ansible_distribution_major_version == "7") or
    ansible_distribution == 'Amazon'

- name: Install the latest version of firewalld EL/CentOS 8 & 9
  dnf:
    name: firewalld
    state: present
  when:
    - ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
    - ansible_distribution_major_version == "8" or ansible_distribution_major_version == "9"

- name: Enable firewalld service
  systemd:
    name: firewalld
    state: started

- name: Get active firewalld zone
  shell: "firewall-cmd --list-all | grep active"
  changed_when: false
  failed_when: false
  register: firewalld_zone

- name: Change firewalld zone
  command: "firewall-cmd --zone=dmz --permanent --change-interface={{ ansible_default_ipv4.interface }}"
  when: "'dmz' not in firewalld_zone.stdout"
