---
# Install and enable firewalld service

- name: Install the latest version of firewalld Debian
  apt:
    name: firewalld
    state: present
  when: ansible_os_family == "Debian"

- name: Install the latest version of firewalld EL/CentOS 7 & Amazon
  yum:
    name: firewalld
    state: present
  when: >
    ((ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux') and
    ansible_distribution_major_version == "7") or
    ansible_distribution == 'Amazon'

- name: Install the latest version of firewalld EL/CentOS 8 & 9
  dnf:
    name: firewalld
    state: present
  when:
    - ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
    - ansible_distribution_major_version == "8" or ansible_distribution_major_version == "9"

- name: Enable firewalld service
  systemd:
    name: firewalld
    state: started

- name: Get firewalld default zone
  command: "firewall-cmd --get-default-zone"
  changed_when: false
  failed_when: false
  register: firewalld_def_zone

- name: Set firewalld default zone
  command: "firewall-cmd --set-default-zone=dmz"
  notify: Restart auditd
  when: "'dmz' not in firewalld_def_zone.stdout"

- name: Get active firewalld zone
  command: "firewall-cmd --get-active-zones"
  changed_when: false
  failed_when: false
  register: firewalld_act_zone

- name: Change firewalld zone
  command: "firewall-cmd --zone=dmz --permanent --change-interface={{ ansible_default_ipv4.interface }}"
  notify: Restart auditd
  when: "'(active)' not in firewalld_act_zone.stdout"

- name: Get firewalld log config
  command: "firewall-cmd --get-log-denied"
  changed_when: false
  failed_when: false
  register: firewalld_log

- name: Set firewalld log all
  command: "firewall-cmd --set-log-denied=all"
  notify: Restart auditd
  when: "'all' not in firewalld_log.stdout"
