---
# Tasks file for hardening role

- name: Upgrade all packages Ubuntu
  apt:
    name: '*'
    state: latest
  when: ansible_os_family == "Debian"

- name: Upgrade all packages EL/CentOS 7 & Amazon Linux
  yum:
    name: '*'
    state: latest
  when: >
    ((ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux') and
    ansible_distribution_major_version == "7") or
    ansible_distribution == 'Amazon'

- name: Upgrade all packages EL/CentOS 8 & 9
  dnf:
    name: '*'
    state: latest
  when:
    - ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
    - ansible_distribution_major_version == "8" or ansible_distribution_major_version == "9"

- name: Sysctl setup
  include_tasks: sysctl.yml
  args:
    apply:
      become: yes

- name: Audit setup
  include_tasks: audit.yml
  args:
    apply:
      become: yes

- name: Firewalld setup
  include_tasks: firewall.yml
  args:
    apply:
      become: yes

- name: SELinux setup
  include_tasks: selinux.yml
  args:
    apply:
      become: yes

- name: Set root password variable
  set_fact:
    root_password: "{{ lookup('env', 'ROOT_PASSWORD') }}"

- name: Root password change
  user:
    name: root
    password: "{{ root_password | password_hash('sha512') }}"

- name: Users configuration
  include_tasks: users.yml
  args:
    apply:
      become: yes
...
