---
# Minimize permissions of important files

- name: Find files with write-permissions for group
  shell: "find -L {{ item }} -perm /go+w -type f"  # noqa command-instead-of-shell
  loop:
    - '/usr/local/sbin'
    - '/usr/local/bin'
    - '/usr/sbin'
    - '/usr/bin'
    - '/sbin'
    - '/bin'
  register: minimize_access_directories
  ignore_errors: true
  changed_when: false

- name: Minimize access on found files
  file:
    path: '{{ item.1 }}'
    mode: 'go-w'
    state: file
  with_subelements:
    - "{{ minimize_access_directories.results }}"
    - stdout_lines

- name: Find shadow files
  stat:
    path: "{{ item }}"
  loop:
    - '/etc/shadow'
    - '/etc/gshadow'
    - '/etc/shadow-'
    - '/etc/gshadow-'
  register: minimize_access_shadow_files

- name: Change shadow ownership to root and mode to 0600 | os-02
  file:
    dest: "{{ item.item }}"
    owner: root
    group: shadow
    mode: u=rw,g=r,o=
  when: item.stat.exists
  loop: "{{ minimize_access_shadow_files.results }}"

- name: Find passwd files
  stat:
    path: "{{ item }}"
  loop:
    - '/etc/passwd'
    - '/etc/group'
    - '/etc/passwd-'
    - '/etc/group-'
  register: minimize_access_passwd_files

- name: Change passwd ownership to root and mode to 0644 | os-03
  file:
    dest: "{{ item.item }}"
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  when: item.stat.exists
  loop: "{{ minimize_access_passwd_files.results }}"

- name: Change su-binary to only be accessible to user and group root
  file:
    dest: '/bin/su'
    owner: 'root'
    group: 'root'
    mode: '0750'
