---
# Install and enable SELinux

- name: Install libselinux-python Amazon
  yum:
    name: libselinux-python
    state: present
  when: ansible_distribution == 'Amazon'

- name: Install python3-selinux Debian
  apt:
    name: python3-selinux
    state: present
  when: ansible_os_family == "Debian"

- name: Install python3-libselinux EL/CentOS
  yum:
    name: python3-libselinux
    state: present
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Install SELinux Debian
  apt:
    pkg:
      - selinux-utils
      - selinux-basics
    state: present
  when: ansible_os_family == "Debian"

- name: Enable SELinux Debian
  selinux:
    policy: default
    state: enforcing
  notify: Reboot
  when: ansible_os_family == "Debian"

- name: Enable SELinux EL/CentOS/Amazon
  selinux:
    policy: targeted
    state: enforcing
  notify: Reboot
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux' or ansible_distribution == 'Amazon'
