---
# Install and enable SELinux

- name: Install libselinux-python Amazon
  yum:
    name: libselinux-python
    state: present
  when: ansible_distribution == 'Amazon'

- name: Install python3-libselinux EL/CentOS/Debian
  yum:
    name: python3-libselinux
    state: present
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux' or ansible_os_family == "Debian"

- name: Install selinux Ubuntu
  apt:
    pkg:
      - selinux-utils
      - selinux-basics
    state: present
  when: ansible_os_family == "Debian"

- name: Enable SELinux
  selinux:
    policy: targeted
    state: enforcing
  notify: Reboot
