---
# Configure low-level protective Linux kernel parameters at runtime

- name: Change kernel parameters
  vars:
    sysctl_config:
      net.ipv4.conf.all.accept_redirects: 0 # Disable ICMP redirect acceptance
      net.ipv4.conf.all.accept_source_route: 0 # Disable IP source routing
      net.ipv4.conf.all.log_martians: 1 # Enable logging of spoofed packets, source routed packets and redirect packets
      net.ipv4.conf.all.rp_filter: 1 # Enable IP spoofing protection
      net.ipv4.conf.all.secure_redirects: 0
      net.ipv4.conf.all.send_redirects: 0
      net.ipv4.conf.default.accept_redirects: 0 # Disable ICMP redirect acceptance
      net.ipv4.conf.default.accept_source_route: 0 # Disable IP source routing
      net.ipv4.conf.default.log_martians: 1 # Enable logging of spoofed packets, source routed packets and redirect packets
      net.ipv4.conf.default.rp_filter: 1
      net.ipv4.conf.default.secure_redirects: 0
      net.ipv4.conf.default.send_redirects: 0
      net.ipv4.icmp_echo_ignore_all: 1 # Enable ignoring to ICMP requests
      net.ipv4.icmp_echo_ignore_broadcasts: 1 # Enable ignoring to ICMP ECHO and TIMESTAMP requests via broadcast
      net.ipv4.icmp_ignore_bogus_error_responses: 1 # Ignore bad ICMP errors
      net.ipv4.ip_forward: 0 # Controls IP packet forwarding
      net.ipv4.tcp_max_syn_backlog: 1280
      net.ipv4.tcp_syncookies: 1 # Enable TCP SYN cookie protection
      net.ipv4.tcp_synack_retries: 5 # Turn on SYN-flood protections
      net.ipv4.tcp_timestamps: 0
      net.ipv4.tcp_fin_timeout: 30 # How much seconds keep sockets in FIN-WAIT-2 state for a shutdown from the remote end
      net.ipv4.tcp_keepalive_time: 1800 # How often to send TCP keepalive packets to keep an connection alive if it is currently unused
      net.ipv6.conf.all.accept_ra: 0
      net.ipv6.conf.all.accept_redirects: 0 # Disable ICMP redirect acceptance
      net.ipv6.conf.all.accept_source_route: 0 # Disable IP source routing
      net.ipv6.conf.all.disable_ipv6: 1 # Disable IPv6
      net.ipv6.conf.all.autoconf: 0
      net.ipv6.conf.default.accept_ra: 0
      net.ipv6.conf.default.accept_ra_rtr_pref: 0 # Accept Router Preference in RA?
      net.ipv6.conf.default.accept_ra_pinfo: 0 # Learn Prefix Information in Router Advertisement
      net.ipv6.conf.default.accept_ra_defrtr: 0 # Setting controls whether the system will accept Hop Limit settings from a router advertisement
      net.ipv6.conf.default.accept_redirects: 0 # Disable ICMP redirect acceptance
      net.ipv6.conf.default.accept_source_route: 0 # Disable IP source routing
      net.ipv6.conf.default.disable_ipv6: 1 # Disable IPv6
      net.ipv6.conf.default.router_solicitations: 0 # Number of Router Solicitations to send until assuming no routers are present
      net.ipv6.conf.default.autoconf: 0 # Router advertisements can cause the system to assign a global unicast address to an interface
      net.ipv6.conf.default.dad_transmits: 0 # How many neighbor solicitations to send out per address
      net.ipv6.conf.default.max_addresses: 1 # How many global unicast IPv6 addresses can be assigned to each interface
      net.core.somaxconn: 65535 # Change the amount of incoming connections
      net.core.netdev_max_backlog: 262144 # Change the amounf of incoming connections backlog
      net.core.optmem_max: 25165824 # Increase the maximum amount of memory buffers
      net.core.rmem_default: 31457280 # Increase the default receive buffers
      net.core.rmem_max: 67108864 # Increase the maximum receive buffers
      net.core.wmem_default: 31457280 # Increase the default send buffers
      net.core.wmem_max: 67108864 # Increase the maximum send buffers
      vm.swappiness: 20 # Minimizing the amount of swapping
      vm.dirty_ratio: 80
      vm.dirty_background_ratio: 5
      fs.file-max: 65535 # Increases the size of file handles and inode cache
      fs.suid_dumpable: 0 # Restricts core dumps
      fs.protected_hardlinks: 1 # Protects against creating or following links under certain conditions
      fs.protected_symlinks: 1 # Protects against creating or following links under certain conditions
      kernel.pid_max: 65536 # Allow for more PIDs
      kernel.sysrq: 0 # Controls the System Request debugging functionality of the kernel
      kernel.core_uses_pid: 1 # Controls whether core dumps will append the PID to the core filename. Useful for debugging multi-threaded applications
      kernel.randomize_va_space: 2 # Addresses of mmap base, heap, stack and VDSO page are randomized
  sysctl:
    name: '{{ item.key }}'
    value: '{{ item.value }}'
    sysctl_set: yes
    state: present
    reload: yes
    ignoreerrors: yes
  with_dict: '{{ sysctl_config }}'
