---
- hosts: servers
  become: true
  pre_tasks:
    - debug:
        var: run_crowdsec
  roles:
    - role: crowdsec
      tags: ['crowdsec']
      when: run_crowdsec | bool == true

    - role: hardening
      tags: ['hardening']
      when: run_hardening
