---
- hosts: servers
  become: true
  vars:
    run_crowdsec: true
    run_hardening: true
    run_notify: true
  pre_tasks:
    - debug:
        var: run_crowdsec
  roles:
    - role: crowdsec
      tags: ['crowdsec']
      when: run_crowdsec | bool == true

    - role: hardening
      tags: ['hardening']
      when: run_hardening | bool == true

    - role: notify
      tags: ['notify']
      when: run_notify | bool == true
