# It's highly recommended to avoid this auto-merge process because it could introduce vulnerable dependencies.
# However, it's used here as this repository is intended to be used only in controlled development environments.
# See [README.md](/README.md) for more information.

name: Dependabot auto-merge
on: 
  pull_request:
    branches:
      - 'dependabot/pip/ansible-lint-**'
      - 'dependabot/pip/ansible-**'
      - 'dependabot/github_actions/dot-github/workflows/actions/checkout-**'
      - 'dependabot/github_actions/dot-github/workflows/actions/setup-python-**'
      - 'dependabot/github_actions/dot-github/workflows/ansible-community/ansible-lint-action-**'
      - 'dependabot/github_actions/dot-github/workflows/dependabot/fetch-metadata-**'
    paths:
      - '.github/workflows/dependabot-automerge.yml'
      - '.github/workflows/hardening.yml'
      - '.github/workflows/lint.yml'
      - 'requirements.txt'

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot:
    name: Dependabot PRs approve and auto-merge
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@4de7a6c08ce727a42e0adbbdc345f761a01240ce
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Auto-merge Dependabot PRs
        if: >
          (
               steps.metadata.outputs.update-type == 'version-update:semver-patch'
            || steps.metadata.outputs.update-type == 'version-update:semver-minor'
          ) && (
               steps.metadata.outputs.dependency-names == 'ansible'
            || steps.metadata.outputs.dependency-names == 'ansible-lint'
          )
        run: |
          gh pr review --approve "$PR_URL"
          gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}