name: Hardening
on: 
  workflow_dispatch:
    inputs:
      ip:
        description: Server IP Address
        required: true

jobs:
  validate:
    name: Validate Ansible code
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout main
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
        with:
          fetch-depth: 0
      - name: Run ansible-lint
        uses: ansible-community/ansible-lint-action@27c37f9001153675ee6abcadcd722bcbdafaba08
        with:
          path: "ansible/"

  ansible:
    name: Run Ansible hardening playbook
    runs-on: ubuntu-latest
    needs: [ validate ]
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout main
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
        with:
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@13a464fa1180c0025831475fa35bb1878b1a4728
        with:
          python-version: '3.10'
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Convert inventory templates
        env:
          SERVER_IP: ${{ github.event.inputs.ip }}
        run: |
          for file in `find ansible/inventory/ -type f -name '*.tpl'`;
          do
          envsubst < "$file" > ${file%".tpl"};
          done
      - name: Prepare SSH key
        env:
          ANSIBLE_KEY: ${{ secrets.ANSIBLE_KEY }}
        run: |
          echo -n ${ANSIBLE_KEY} > ansible/config/ansible.key
          chmod 600 ansible/config/ansible.key
      - name: Check hosts
        run: |
         whoami
         ansible --version
         ansible \
          --inventory ansible/inventory/hosts.yml \
          -m ping all
      - name: Deploy Ansible
        run: |
          ansible-playbook ansible/main.yml \
            --diff \
            --inventory ansible/inventory/inventory.yml