name: Hardening
on: 
  workflow_dispatch:
    inputs:
      ip:
        description: Server IP Address
        required: true
        type: string
      console_name:
        description: Server name for CrowdSec Console
        required: true
        type: string
      ssh_user:
        description: SSH username
        required: true
        type: string
      run_crowdsec:
        description: Run crowdsec role
        default: true
        required: true
        type: boolean
      run_hardening:
        description: Run hardening role
        default: true
        required: true
        type: boolean
      run_notify:
        description: Run notify role
        default: true
        required: true
        type: boolean

jobs:
  ansible_lint:
    uses: ./.github/workflows/lint.yml
  ansible_playbook:
    name: Run Ansible hardening playbook
    runs-on: ubuntu-latest
    needs: [ ansible_lint ]
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout main
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
        with:
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3
        with:
          python-version: '3.10'
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Convert inventory templates
        env:
          SERVER_IP: ${{ inputs.ip }}
        run: |
          for file in `find ansible/inventory/ -type f -name '*.tpl'`;
          do
          envsubst < "$file" > ${file%".tpl"};
          done
      - name: Convert ansible config template
        env:
          SSH_USER: ${{ inputs.ssh_user }}
        run: envsubst < ansible/ansible.cfg.tpl > ansible/ansible.cfg
      - name: Prepare SSH key
        run: |
          echo "${{ secrets.ANSIBLE_KEY }}" | base64 -d > ansible/config/ansible.key
          chmod 600 ansible/config/ansible.key
      - name: Check hosts
        env:
          ANSIBLE_CONFIG: ansible/ansible.cfg
        run: |
         whoami
         ansible --version
         ansible \
          --inventory ansible/inventory/inventory.yml \
          -m ping all
      - name: Deploy Ansible
        env:
          ANSIBLE_CONFIG: ansible/ansible.cfg
          CONSOLE_NAME: ${{ inputs.console_name }}
          CONSOLE_KEY: ${{ secrets.CONSOLE_KEY }}
          DASHBOARD_PASSWORD: ${{ secrets.DASHBOARD_PASSWORD }}
          ROOT_PASSWORD: ${{ secrets.ROOT_PASSWORD }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_ID_CHAT: ${{ secrets.TELEGRAM_ID_CHAT }}
        run: |
          ansible-playbook ansible/main.yml \
            --diff \
            --inventory ansible/inventory/inventory.yml \
            --extra-vars "run_crowdsec=${{ inputs.run_crowdsec }} run_hardening=${{ inputs.run_hardening }} run_notify=${{ inputs.run_notify }}"