name: Hardening
on: 
  workflow_dispatch:
    inputs:
      ip:
        description: Server IP Address
        required: true
      console_name:
        description: Server name for CrowdSec Console
        required: true
      ssh_user:
        description: SSH username
        required: true

jobs:
  validate:
    name: Validate Ansible code
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout main
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
        with:
          fetch-depth: 0
      - name: Run ansible-lint
        uses: ansible-community/ansible-lint-action@27c37f9001153675ee6abcadcd722bcbdafaba08
        with:
          path: "ansible/"

  ansible:
    name: Run Ansible hardening playbook
    runs-on: ubuntu-latest
    needs: [ validate ]
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout main
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
        with:
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@13ae5bb136fac2878aff31522b9efb785519f984
        with:
          python-version: '3.10'
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Convert inventory templates
        env:
          SERVER_IP: ${{ github.event.inputs.ip }}
        run: |
          for file in `find ansible/inventory/ -type f -name '*.tpl'`;
          do
          envsubst < "$file" > ${file%".tpl"};
          done
      - name: Convert ansible config template
        env:
          SSH_USER: ${{ github.event.inputs.ssh_user }}
        run: envsubst < ansible/ansible.cfg.tpl > ansible/ansible.cfg
      - name: Prepare SSH key
        run: |
          echo "${{ secrets.ANSIBLE_KEY }}" | base64 -d > ansible/config/ansible.key
          chmod 600 ansible/config/ansible.key
      - name: Check hosts
        env:
          ANSIBLE_CONFIG: ansible/ansible.cfg
        run: |
         whoami
         ansible --version
         ansible \
          --inventory ansible/inventory/inventory.yml \
          -m ping all
      - name: Deploy Ansible
        env:
          ANSIBLE_CONFIG: ansible/ansible.cfg
          CONSOLE_NAME: ${{ github.event.inputs.console_name }}
          CONSOLE_KEY: ${{ secrets.CONSOLE_KEY }}
          DASHBOARD_PASSWORD: ${{ secrets.DASHBOARD_PASSWORD }}
        run: |
          ansible-playbook ansible/main.yml \
            --diff \
            --inventory ansible/inventory/inventory.yml