name: Ansible Lint
on: 
  pull_request:
    branches: [ main ]
    paths:
      - 'ansible/**'
  push:
    branches: [ main ]
    paths:
      - 'ansible/**'
  workflow_call:

jobs:
  ansible_lint:
    name: Validate Ansible code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3
        with:
          fetch-depth: 0
      - name: Run ansible-lint
        uses: ansible-community/ansible-lint-action@00bab8f19cddd45b04ba28dc38e5d9a2a1b1366c
        with:
          path: "ansible/"