name: Ansible Lint
on: 
  pull_request:
    branches: [ main ]
    paths:
      - 'ansible/**'
  push:
    branches: [ main ]
    paths:
      - 'ansible/**'
  workflow_call:

jobs:
  ansible_lint:
    name: Validate Ansible code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633
        with:
          fetch-depth: 0
      - name: Run ansible-lint
        uses: ansible-community/ansible-lint-action@cad5176ea6f24a38f909d688bd467ec8d942d7e1
        with:
          path: "ansible/"