name: Ansible Lint
on: 
  pull_request:
    branches: [ main ]
    paths:
      - 'ansible/**'
  push:
    branches: [ main ]
    paths:
      - 'ansible/**'
  workflow_call:

jobs:
  ansible_lint:
    name: Validate Ansible code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
        with:
          fetch-depth: 0
      - name: Run ansible-lint
        uses: ansible-community/ansible-lint-action@912d1bf4240f503c2b7e50a6cacadd7df5c3dd82
        with:
          path: "ansible/"